import React, { createContext, useContext, useState, useEffect } from "react";
import { Language } from "@/types";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Extended translations with all new fields
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.users": "Manage Users",
    "nav.assets": "Manage Assets",
    "nav.posts": "Post News",
    "nav.profile": "Update Profile",
    "nav.whatsNew": "What's New",
    "nav.addUser": "Add New User",
    "nav.adminPortal": "Admin Portal",

    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.welcome": "Welcome to Sunday School Portal",
    "auth.logout": "Logout",
    "auth.welcomeDescription":
      "Welcome back to your spiritual community. Sign in to continue your journey.",
    "auth.emailPlaceholder": "your@email.com",
    "auth.passwordPlaceholder": "••••••••",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot Password?",
    "auth.signingIn": "Signing in...",
    "auth.noAccount": "Don't have an account?",
    "auth.demoCredentials": "Demo Credentials",
    "auth.adminAccess": "Admin Access",
    "auth.memberAccess": "Member Access",
    "auth.communityText": "Join our growing spiritual community",
    "auth.weeklySessions": "Weekly Sessions",
    "auth.satisfaction": "Satisfaction",
    "auth.support": "Support",
    "auth.loginError": "Invalid email or password. Please try again.",
    "auth.admin": "Administrator",
    "auth.logoutDesc": "Log out from your account",
    "auth.lastLogin": "Last login",
    // Add these to the existing 'en' translations

    "auth.logoutSuccess": "Logged out successfully",
    "nav.settings": "Settings",
    "common.user": "User",

    // Add these to the existing 'en' translations
    "signup.title": "Join Our Spiritual Family",
    "signup.subtitle":
      "Begin your journey with our Sunday School community. Complete your registration to access spiritual guidance, lessons, and a supportive network of believers.",
    "signup.spiritualBenefits": "Spiritual Benefits",
    "signup.bibleLearning": "Bible-Based Learning",
    "signup.bibleLearningDesc":
      "Structured lessons that help you understand and apply biblical teachings in daily life.",
    "signup.faithCommunity": "Faith Community",
    "signup.faithCommunityDesc":
      "Connect with like-minded individuals who share your spiritual values and goals.",
    "signup.personalGrowth": "Personal Growth",
    "signup.personalGrowthDesc":
      "Tools and resources to support your spiritual development at every stage.",
    "signup.communitySupport": "Community Support",
    "signup.prayerGroups": "Prayer Groups",
    "signup.familyEvents": "Family Events",
    "signup.mentorshipPrograms": "Mentorship Programs",
    "signup.spiritualGuidance": "Spiritual Guidance",
    "signup.safeEnvironment": "Safe Environment",
    "signup.safeEnvironmentDesc":
      "Our platform maintains the highest standards of safety and privacy. All activities are monitored to ensure a secure spiritual environment for everyone.",
    "signup.studentRegistration": "Student Registration",
    "signup.registrationDesc":
      "Please provide all required information to complete your spiritual journey registration",
    "signup.backToLogin": "Back to Login",

    "userForm.createTitle": "Register New Student",
    "userForm.editTitle": "Update User Profile",
    "userForm.createSubtitle":
      "Complete all required information to register a new student",
    "userForm.editSubtitle": "Update user information and personal details",
    "userForm.editingOwnProfile": "Editing Your Own Profile",
    "userForm.personalInfo": "Personal Information",
    "userForm.studentId": "Student ID",
    "userForm.firstName": "First Name",
    "userForm.middleName": "Middle Name",
    "userForm.lastName": "Last Name",
    "userForm.sex": "Sex",
    "userForm.male": "Male",
    "userForm.female": "Female",
    "userForm.email": "Email Address",
    "userForm.phone": "Phone Number",
    "userForm.dateOfBirth": "Date of Birth",
    "userForm.nationalId": "National ID",
    "userForm.occupation": "Occupation",
    "userForm.marriageStatus": "Marriage Status",
    "userForm.single": "Single",
    "userForm.married": "Married",
    "userForm.divorced": "Divorced",
    "userForm.widowed": "Widowed",
    "userForm.disabilityInfo": "Disability Information",
    "userForm.hasDisability": "Has Disability?",
    "userForm.disabilityType": "Disability Type",
    "userForm.locationInfo": "Location",
    "userForm.country": "Country",
    "userForm.region": "Region",
    "userForm.zone": "Zone",
    "userForm.woreda": "Woreda",
    "userForm.church": "Church",
    "userForm.parentInfo": "Parent/Guardian",
    "userForm.parentStatus": "Parent Status",
    "userForm.bothParents": "Both Parents",
    "userForm.motherOnly": "Mother Only",
    "userForm.fatherOnly": "Father Only",
    "userForm.guardian": "Guardian",
    "userForm.parentFullName": "Full Name",
    "userForm.parentEmail": "Email",
    "userForm.parentPhone": "Phone Number",
    "userForm.cancel": "Cancel",
    "userForm.createStudent": "Create Student",
    "userForm.updateProfile": "Update Profile",
    "userForm.saving": "Saving...",
    "userForm.requiredFields": "Please fill in all required fields",

    "profile.title": "Profile Settings",
    "profile.subtitle": "Manage your personal information and account settings",
    "profile.editingProfile": "Editing Your Profile",
    "profile.personalInfo": "Personal Information",
    "profile.locationInfo": "Location Information",
    "profile.accountSecurity": "Account Security",
    "profile.changePassword": "Change Password",
    "profile.currentPassword": "Current Password",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm New Password",
    "profile.passwordRequirements": "Password Requirements",
    "profile.passwordRequirement1": "At least 8 characters long",
    "profile.passwordRequirement2": "Include uppercase and lowercase letters",
    "profile.passwordRequirement3": "Include at least one number",
    "profile.passwordRequirement4": "Include at least one special character",
    "profile.memberStats": "Member Stats",
    "profile.attendance": "Attendance",
    "profile.activities": "Activities",
    "profile.memberSince": "Member Since",
    "profile.sundaySchoolMember": "Sunday School Member",
    "profile.joined": "Joined",
    "profile.saveChanges": "Save Changes",
    "profile.updating": "Updating...",
    "profile.saving": "Saving...",
    "profile.profilePictureUpdated": "Profile picture updated",
    "profile.photoSaved": "Your new photo has been saved",
    "profile.fileTooLarge": "File too large",
    "profile.fileSizeError": "Please choose an image smaller than 5MB",
    "profile.passwordsNoMatch": "Passwords do not match",
    "profile.passwordTooShort": "Password must be at least 8 characters long",
    "profile.passwordUpdated": "Password updated successfully",
    "profile.passwordChangeSuccess": "Your password has been changed",
    "profile.passwordChangeError": "Failed to update password",
    "profile.passwordCheckError":
      "Please check your current password and try again",
    "profile.profileUpdated": "Profile updated successfully",
    "profile.changesSaved": "Your changes have been saved",
    "profile.updateError": "Failed to update profile",
    "profile.personal": "Personal Information",
    "profile.details": "Location & Background",
    "profile.account": "Change Password",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.phone": "Phone",
    "profile.aboutMe": "About Me",
    "profile.address": "Address",
    "profile.city": "City",
    "profile.country": "Country",
    "profile.occupation": "Occupation",
    "profile.education": "Education",
    "profile.sundaySchool": "Sunday School",
    "profile.responsibility": "Responsibility",
    "profile.avatar": "Profile Picture",
    "profile.updateInfo": "Edit your personal information",
    // Add these to the 'en' translations object:
    "profile.editProfile": "Edit Your Profile",
    "profile.updatePersonalInfo":
      "Update your personal information, contact details, and preferences",
    "profile.accountSecurityDesc":
      "Your account is secured with the latest encryption standards. Regular security updates ensure your data remains protected.",
    "profile.lastUpdated": "Last updated",
    "profile.membership": "Membership",
    "profile.studentId": "Student ID",
    "profile.status": "Status",
    "profile.currentGrade": "Current Grade",
    "profile.loadingProfile": "Loading profile...",
    "profile.tryAgainLater": "Please try again later.",

    // Common
    "common.save": "Save Changes",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.role": "Role",
    "common.active": "Active",
    "common.inactive": "Inactive",

    // User Fields
    "user.studentId": "Student ID",
    "user.middleName": "Middle Name",
    "user.sex": "Sex",
    "user.phoneNumber": "Phone Number",
    "user.disability": "Disability",
    "user.disabilityType": "Disability Type",
    "user.dateOfBirth": "Date of Birth",
    "user.region": "Region",
    "user.zone": "Zone",
    "user.woreda": "Woreda",
    "user.church": "Church",
    "user.marriageStatus": "Marriage Status",
    "user.parentStatus": "Parent Status",
    "user.parentFullName": "Parent Full Name",
    "user.parentEmail": "Parent Email",
    "user.parentPhoneNumber": "Parent Phone Number",
    "user.nationalId": "National ID",
    "user.occupation": "Occupation",
    "users.noUsersSelected": "No users selected",
    "users.cannotDeleteOwnAccount": "Cannot delete your own account",
    "users.deletedSuccess": "{{count}} user(s) deleted successfully",
    "users.userDeleted": "User deleted successfully",
    "users.admins": "Admins",
    "users.allStatus": "All Status",
    "users.allRoles": "All Roles",
    "users.exportUsers": "Export Users",
    "users.noUsersFound": "No users found",
    "users.tryAdjustingSearch": "Try adjusting your search terms",
    "users.noUsersAvailable": "No users available in the system",
    "users.userDetails": "User Details",
    "userForm.userUpdated": "User updated successfully",
    "userForm.userCreated": "User created successfully",

    // Dashboard
    "dashboard.overview": "Overview of your Sunday School management system",
    "dashboard.totalUsers": "Total Users",
    "dashboard.totalAssets": "Total Assets",
    "dashboard.activePosts": "Active Posts",
    "dashboard.engagement": "Engagement Rate",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.fromLastMonth": "from last month",
    "dashboard.viewAll": "View all",
    "dashboard.viewDetails": "View details",
    "dashboard.activityDetails": "Activity Details",
    "dashboard.action": "Action",
    "dashboard.time": "Time",
    "dashboard.user": "User",
    "dashboard.email": "Email",
    "dashboard.details": "Details",
    "dashboard.exportReport": "Export Report",
    "dashboard.exportDetails": "Export Details",
    "dashboard.close": "Close",
    "dashboard.newUserRegistered": "New user registered",
    "dashboard.assetUpdated": "Asset updated",
    "dashboard.newPostPublished": "New post published",
    "dashboard.completedRegistration":
      "Completed registration with all required information.",
    "dashboard.updatedAssetStatus": "Updated asset status to Available.",
    "dashboard.publishedWelcomePost": "Published welcome post",
    "dashboard.hoursAgo": "hours ago",
    "dashboard.daysAgo": "days ago",
    // In the 'en' translations object:
    "dashboard.welcomeMessage":
      "Welcome back, {{name}}! Here's what's happening today.",
    "dashboard.usersDescription": "Registered users",
    "dashboard.assetsDescription": "Church assets",
    "dashboard.postsDescription": "Active posts",
    "dashboard.engagementDescription": "User participation",
    "dashboard.activeUsers": "Active Users",
    "dashboard.livePosts": "Live Posts",
    "dashboard.availableAssets": "Available Assets",

    // "dashboard.quickActions": {
    //   title: "Quick Actions",
    //   subtitle: "Frequently used tasks",
    //   addUser: "Add New User",
    //   addUserDesc: "Register a new student or teacher",
    //   manageAssets: "Manage Assets",
    //   manageAssetsDesc: "View and manage church assets",
    //   createPost: "Create Post",
    //   createPostDesc: "Share news and announcements",
    //   viewReports: "View Reports",
    //   viewReportsDesc: "Analytics and insights",
    // },
    "dashboard.recentActivitySubtitle": "Latest system activities",
    "dashboard.systemOverview": "System Overview",
    "dashboard.systemOverviewSubtitle": "Performance metrics and insights",
    "dashboard.systemUptime": "System Uptime",
    "dashboard.last30Days": "Last 30 days",
    "dashboard.activeMonitoring": "Active Monitoring",
    "dashboard.realTimeUpdates": "Real-time updates",
    "dashboard.dataAccuracy": "Data Accuracy",
    "dashboard.verifiedInformation": "Verified information",

    // Add these to the 'en' translations object:
    "userDashboard.welcomeBack": "Welcome Back, {{name}}!",
    "userDashboard.welcomeMessage":
      "Here's what's happening in your Sunday School journey today.",
    "userDashboard.currentGrade": "Current Grade",
    "userDashboard.streakDays": "Streak Days",
    "userDashboard.yourChurch": "Your Church",
    "userDashboard.myClasses": "My Classes",
    "userDashboard.activeEnrollments": "Active enrollments",
    "userDashboard.assignedAssets": "Assigned Assets",
    "userDashboard.resourcesAssigned": "Resources assigned to you",
    "userDashboard.attendance": "Attendance",
    "userDashboard.thisMonth": "This month",
    "userDashboard.activities": "Activities",
    "userDashboard.completedThisYear": "Completed this year",
    "userDashboard.quickActions": "Quick Actions",
    "userDashboard.viewAnnouncements": "View Announcements",
    "userDashboard.checkLatestNews": "Check latest news and updates",
    "userDashboard.updateProfile": "Update Profile",
    "userDashboard.keepInformationCurrent": "Keep your information current",
    "userDashboard.myResources": "My Resources",
    "userDashboard.viewAssignedBooks": "View assigned books and materials",
    "userDashboard.classSchedule": "Class Schedule",
    "userDashboard.viewTimetable": "View your class timetable",
    "userDashboard.upcomingEvents": "Upcoming Events",
    "userDashboard.bibleStudySession": "Bible Study Session",
    "userDashboard.youthFellowship": "Youth Fellowship",
    "userDashboard.sundayService": "Sunday Service",
    "userDashboard.mainHall": "Main Hall",
    "userDashboard.youthCenter": "Youth Center",
    "userDashboard.mainChurch": "Main Church",
    "userDashboard.class": "class",
    "userDashboard.event": "event",
    "userDashboard.service": "service",
    "userDashboard.recentAnnouncements": "Recent Announcements",
    "userDashboard.noAnnouncements": "No announcements yet",
    "userDashboard.checkBackLater": "Check back later for updates",
    "userDashboard.viewAllAnnouncements": "View All Announcements",
    "userDashboard.learningProgress": "Learning Progress",
    "userDashboard.currentLevel": "Current Level",
    "userDashboard.gradeIntermediate": "Grade 3 - Intermediate",
    "userDashboard.bibleKnowledge": "Bible Knowledge",
    "userDashboard.prayerWorship": "Prayer & Worship",
    "userDashboard.churchHistory": "Church History",
    "userDashboard.badges": "Badges",
    "userDashboard.goalsMet": "Goals Met",
    "userDashboard.sessions": "Sessions",
    "userDashboard.level": "Level",

    // Users
    "users.manage": "Manage Users",
    "users.viewManage": "View and manage all registered users",
    "users.searchPlaceholder": "Search users...",
    "users.user": "User",
    "users.viewDetails": "View Details",

    // Assets
    "assets.manage": "Manage Assets",
    "assets.overview": "Track and manage all church assets",
    "assets.addNew": "Register New Asset",
    "assets.code": "Asset Code",
    "assets.name": "Name",
    "assets.category": "Category",
    "assets.assignedTo": "Assigned To",
    "assets.purchaseDate": "Purchase Date",
    "assets.description": "Description",
    "assets.purchasePrice": "Purchase Price",
    "assets.location": "Location",
    "assets.condition": "Condition",
    "assets.supplier": "Supplier",
    "assets.serialNumber": "Serial Number",
    "assets.warrantyExpiry": "Warranty Expiry",
    "assetForm.createTitle": "Register New Asset",
    "assetForm.editTitle": "Update Asset",
    "assetForm.createSubtitle": "Add new asset to the church inventory",
    "assetForm.editSubtitle": "Update asset information and details",
    "assetForm.basicInfo": "Basic Information",
    "assetForm.assetCode": "Asset Code",
    "assetForm.assetName": "Asset Name",
    "assetForm.description": "Description",
    "assetForm.category": "Category",
    "assetForm.status": "Status",
    "assetForm.assignedTo": "Assigned To",
    "assetForm.condition": "Condition",
    "assetForm.purchaseDetails": "Purchase Details",
    "assetForm.purchaseDate": "Purchase Date",
    "assetForm.purchasePrice": "Purchase Price",
    "assetForm.supplier": "Supplier",
    "assetForm.locationId": "Location & ID",
    "assetForm.location": "Location",
    "assetForm.serialNumber": "Serial Number",
    "assetForm.warrantyExpiry": "Warranty Expiry",
    "assetForm.tags": "Tags",
    "assetForm.addTag": "Add tag...",
    "assetForm.add": "Add",
    "assetForm.cancel": "Cancel",
    "assetForm.createAsset": "Create Asset",
    "assetForm.updateAsset": "Update Asset",
    "assetForm.saving": "Saving...",
    "assetForm.requiredFields": "Please fill in all required fields",
    "assetForm.assetCreated": "Asset created successfully!",
    "assetForm.assetAdded": "has been added to the inventory.",
    "assetForm.assetUpdated": "Asset updated successfully!",
    "assetForm.assetChangesSaved": "Asset information has been updated.",
    "assetForm.saveError": "Failed to save asset",

    "assets.totalAssets": "Total Assets",
    "assets.available": "Available",
    "assets.assigned": "Assigned",
    "assets.allStatus": "All Status",
    "assets.allCategories": "All Categories",
    "assets.assetDetails": "Asset Details",
    "assets.noAssetsFound": "No assets found",
    "assets.tryAdjustingSearch": "Try adjusting your search terms",
    "assets.noAssetsAvailable": "No assets available in the system",
    "assets.exportAssets": "Export Assets",
    "assets.deleteSelected": "Delete Selected",
    "assets.registerNewAsset": "Register New Asset",
    "assets.editAsset": "Edit Asset",
    "assets.notAssigned": "Not assigned",
    "assets.unknownUser": "Unknown user",
    // "assetForm.categories": {
    //   "Books": "Books",
    //   "Furniture": "Furniture",
    //   "Electronics": "Electronics",
    //   "Musical Instruments": "Musical Instruments",
    //   "Teaching Materials": "Teaching Materials",
    //   "Sports Equipment": "Sports Equipment",
    //   "Kitchen Supplies": "Kitchen Supplies",
    //   "Cleaning Supplies": "Cleaning Supplies",
    //   "Office Supplies": "Office Supplies",
    //   "Religious Items": "Religious Items",
    //   "Audio Visual": "Audio Visual",
    //   "Computers": "Computers",
    //   "Vehicles": "Vehicles",
    //   "Other": "Other"
    // },
    "assetForm.statuses.maintenance": "Maintenance",
    "assetForm.statuses.retired": "Retired",
    // "assetForm.statuses": {
    //   available: "Available",
    //   assigned: "Assigned",
    //   maintenance: "Maintenance",
    //   retired: "Retired",
    // },
    // "assetForm.conditions": {
    //   "excellent": "Excellent",
    //   "good": "Good",
    //   "fair": "Fair",
    //   "poor": "Poor"
    // }

    // Posts
    "posts.manage": "Post News",
    "posts.overview": "Create and manage news posts",
    "posts.createNew": "Create New Post",
    "posts.title": "Title",
    "posts.content": "Content",
    "posts.author": "Author",
    "posts.date": "Date",
    "nav.userPortal": "User Portal",
    "postForm.createTitle": "Create New Post",
    "postForm.editTitle": "Edit Post",
    "postForm.createSubtitle":
      "Share news, lessons, or announcements with the community",
    "postForm.editSubtitle": "Update your post content and settings",
    "postForm.postContent": "Post Content",
    "postForm.title": "Title",
    "postForm.content": "Content",
    "postForm.featuredImage": "Featured Image URL",
    "postForm.categoriesSettings": "Categories & Settings",
    "postForm.category": "Category",
    "postForm.targetAudience": "Target Audience",
    "postForm.status": "Status",
    "postForm.scheduleOptions": "Schedule & Options",
    "postForm.publishDate": "Publish Date",
    "postForm.expiryDate": "Expiry Date",
    "postForm.pinToTop": "Pin to Top",
    "postForm.pinDescription": "Keep this post at the top of the feed",
    "postForm.tags": "Tags",
    "postForm.addTag": "Add tag...",
    "postForm.add": "Add",
    "postForm.cancel": "Cancel",
    "postForm.publishPost": "Publish Post",
    "postForm.updatePost": "Update Post",
    "postForm.saving": "Saving...",
    "postForm.requiredFields": "Please fill in title and content",
    "postForm.loginRequired": "You must be logged in to create posts",
    "postForm.postCreated": "Post created successfully!",
    "postForm.postPublished": "Your post has been published.",
    "postForm.postUpdated": "Post updated successfully!",
    "postForm.postChangesSaved": "Your post has been updated.",
    "postForm.saveError": "Failed to save post",
    "posts.totalPosts": "Total Posts",
    "posts.published": "Published",
    "posts.pinned": "Pinned",
    "posts.allStatus": "All Status",
    "posts.allCategories": "All Categories",
    "posts.allAudiences": "All Audiences",
    "posts.engagement": "Engagement",
    "posts.audience": "Audience",
    "posts.noPostsFound": "No posts found",
    "posts.tryAdjustingSearch": "Try adjusting your search terms",
    "posts.noPostsAvailable": "No posts available in the system",
    "posts.exportPosts": "Export Posts",
    "posts.deleteSelected": "Delete Selected",
    "posts.createNewPost": "Create New Post",
    "posts.editPost": "Edit Post",
    "posts.tableView": "Table",
    "posts.cardView": "Cards",
    "posts.postDetails": "Post Details",
    "posts.justNow": "Just now",
    "posts.minutesAgo": "m ago",
    "posts.hoursAgo": "h ago",
    "posts.daysAgo": "d ago",
    // "postForm.categories": {
    //   "announcement": "Announcement",
    //   "lesson": "Lesson",
    //   "event": "Event",
    //   "general": "General",
    // },
    // "postForm.audience": {
    //   "all": "Everyone",
    //   "students": "Students Only",
    //   "teachers": "Teachers Only",
    //   "parents": "Parents Only",
    // },
    // "postForm.statuses": {
    //   "draft": "Draft",
    //   "published": "Published",
    //   "archived": "Archived",
    // },

    // In the 'en' translations object:
    "notFound.title": "Page Not Found",
    "notFound.description":
      "Oops! The page you're looking for seems to have wandered off into the digital wilderness. Let's get you back on track.",
    "notFound.goBack": "Go Back",
    "notFound.homePage": "Home Page",
    "notFound.errorCode": "Error Code",
    "notFound.pagesHere": "Pages Here",
    "notFound.possibilities": "Possibilities",
    "notFound.searchSuggestionTitle": "Can't find what you're looking for?",
    "notFound.searchSuggestionDescription":
      "Try using the search feature or navigate through the menu to explore our community platform.",
    "notFound.helpTitle": "Need Help Navigating?",
    "notFound.helpDescription":
      "Here are some popular sections you might be looking for:",
    "notFound.contactSupport": "Still lost?",
    "notFound.contactLink": "Contact Support",

    // Add these to the 'en' translations object:
    "whatsNew.title": "What's New",
    "whatsNew.subtitle":
      "Latest announcements, lessons, and events from your church community",
    "whatsNew.totalPosts": "Total Posts",
    "whatsNew.pinned": "Pinned",
    "whatsNew.announcements": "Announcements",
    "whatsNew.searchPlaceholder": "Search posts...",
    "whatsNew.allCategories": "All Categories",
    "whatsNew.pinnedAnnouncements": "Pinned Announcements",
    "whatsNew.allCommunityPosts": "All Community Posts",
    "whatsNew.noPostsFound": "No posts found",
    "whatsNew.tryAdjustingSearch": "Try adjusting your search terms",
    "whatsNew.noPostsAvailable": "No posts available at the moment",
    "whatsNew.addComment": "Add a comment...",
    "whatsNew.postComment": "Post Comment",
    "whatsNew.comments": "Comments",
    "whatsNew.viewAllComments": "View all comments",
    "whatsNew.hideComments": "Hide comments",
    "whatsNew.loadingComments": "Loading comments...",
    "whatsNew.commentPosted": "Comment posted successfully",
    "whatsNew.failedToPost": "Failed to post comment",
    // Add these to the 'en' translations object:
    "postCard.by": "By",
    "postCard.pinned": "Pinned",
    "postCard.announcement": "Announcement",
    "postCard.lesson": "Lesson",
    "postCard.event": "Event",
    "postCard.students": "Students",
    "postCard.teachers": "Teachers",
    "postCard.parents": "Parents",
    "postCard.everyone": "Everyone",
    "postCard.likes": "likes",
    "postCard.comments": "comments",
    "postCard.shares": "shares",
    "postCard.like": "Like",
    "postCard.comment": "Comment",
    "postCard.share": "Share",
    "postCard.writeComment": "Write a comment...",
    "postCard.commentsTitle": "Comments",
    "postCard.justNow": "Just now",
    "postCard.minutesAgo": "m ago",
    "postCard.hoursAgo": "h ago",
    "postCard.daysAgo": "d ago",
    "postCard.loginToLike": "Please login to like posts",
    "postCard.loginToComment": "Please login to comment",
    "postCard.writeCommentError": "Please write a comment",
    "postCard.commentAdded": "Comment added successfully!",
    "postCard.failedToComment": "Failed to add comment",
    "postCard.loginToLikeComment": "Please login to like comments",
  },
  am: {
    // Amharic translations
    "nav.userPortal": "የተጠቃሚ ፖርታል",

    "nav.dashboard": "ዳሽቦርድ",
    "nav.users": "ተጠቃሚዎችን ያስተዳድሩ",
    "nav.assets": "ንብረቶችን ያስተዳድሩ",
    "nav.posts": "ዜና ያስተዳድሩ",
    "nav.profile": "መገለጫ አዘምን",
    "nav.whatsNew": "አዲስ ምንድን ነው",
    "nav.addUser": "አዲስ ተጠቃሚ ያክሉ",
    "nav.adminPortal": "የአስተዳዳሪ ፖርታል",

    "auth.login": "ግባ",
    "auth.signup": "ተመዝገብ",
    "auth.email": "ኢሜይል",
    "auth.password": "የይለፍ ቃል",
    "auth.welcome": "ወደ የእሁድ ትምህርት ቤት ፖርታል እንኳን በደህና መጡ",
    "auth.logout": "ውጣ",
    "auth.welcomeDescription": "ወደ መንፈሳዊ ማህበረሰብዎ በደህና ተመለሱ። ጉዞዎን ለመቀጠል ይግቡ።",
    "auth.emailPlaceholder": "ኢሜይል@ምሳሌ.ኮም",
    "auth.passwordPlaceholder": "••••••••",
    "auth.rememberMe": "አስታውሰኝ",
    "auth.forgotPassword": "የይለፍ ቃል ረሳኽ?",
    "auth.signingIn": "በመግባት ላይ...",
    "auth.noAccount": "መለያ የሎትም?",
    "auth.admin": "አስተዳዳሪ",
    "auth.logoutDesc": "ከመለያዎ ይውጡ",
    "auth.lastLogin": "የመጨረሻ ግባ",
    // Add these to the existing 'am' translations
    "auth.demoCredentials": "የማሳያ የመግቢያ መለያዎች",
    "auth.adminAccess": "የአስተዳዳሪ መዳረሻ",
    "auth.memberAccess": "የአባል መዳረሻ",
    "auth.communityText": "ወደ እያደገ ከሚገኘው መንፈሳዊ ማህበረሰባችን ይቀላቀሉ",
    "auth.weeklySessions": "የሳምንት አገልግሎቶች",
    "auth.satisfaction": "የደስታ መጠን",
    "auth.support": "ድጋፍ",

    // In the 'am' translations object:
    "auth.logoutSuccess": "በተሳካ ሁኔታ ወጥተዋል",
    "nav.settings": "ማስተካከያዎች",
    "common.user": "ተጠቃሚ",
    // Add these to the existing 'am' translations
    "signup.title": "ወደ መንፈሳዊ ቤተሰባችን ይቀላቀሉ",
    "signup.subtitle":
      "ከእሁድ ትምህርት ቤት ማህበረሰባችን ጋር ጉዞዎን ይጀምሩ። መንፈሳዊ መመሪያ፣ ትምህርቶች እና የደጋግመ ማህበረሰብ ለማግኘት ምዝገባዎን ይጨርሱ።",
    "signup.spiritualBenefits": "መንፈሳዊ ጥቅሞች",
    "signup.bibleLearning": "በመጽሐፍ ቅዱስ የተመሠረተ ትምህርት",
    "signup.bibleLearningDesc":
      "የተዋቀሩ ትምህርቶች የመጽሐፍ ቅዱስ ትምህርቶችን ለመረዳት እና በዕለት ተዕለት ሕይወት ለመተግበር ይረዳሉ።",
    "signup.faithCommunity": "የእምነት ማህበረሰብ",
    "signup.faithCommunityDesc":
      "ከእርስዎ ጋር ተመሳሳይ መንፈሳዊ እሴቶች እና ግቦች ያላቸው ሰዎች ይገናኙ።",
    "signup.personalGrowth": "የግል እድገት",
    "signup.personalGrowthDesc": "መንፈሳዊ እድገትዎን በሁሉም ደረጃ ለመደገፍ መሳሪያዎች እና ሀብቶች።",
    "signup.communitySupport": "የማህበረሰብ ድጋፍ",
    "signup.prayerGroups": "የጸሎት ቡድኖች",
    "signup.familyEvents": "የቤተሰብ ዝግጅቶች",
    "signup.mentorshipPrograms": "የመምሪያ ፕሮግራሞች",
    "signup.spiritualGuidance": "መንፈሳዊ መመሪያ",
    "signup.safeEnvironment": "ደህንነቱ የተጠበቀ አካባቢ",
    "signup.safeEnvironmentDesc":
      "የእኛ መድረክ ከፍተኛ ደህንነት እና ግላዊነት ደረጃዎችን ይጠብቃል። ለሁሉም ሰው ደህንነቱ የተጠበቀ መንፈሳዊ አካባቢ ለማረጋገጥ ሁሉም እንቅስቃሴዎች ይከታተላሉ።",
    "signup.studentRegistration": "የተማሪ ምዝገባ",
    "signup.registrationDesc":
      "የመንፈሳዊ ጉዞ ምዝገባዎን ለማጠናቀቅ እባክዎ ሁሉንም የሚያስፈልጉ መረጃዎች ያቅርቡ",
    "signup.backToLogin": "ወደ መግቢያ ተመለስ",

    "postForm.createTitle": "አዲስ ልጥፍ ፍጠር",
    "postForm.editTitle": "ልጥፍ አርትዕ",
    "postForm.createSubtitle": "ዜና፣ ትምህርቶች ወይም ማስታወቂያዎችን ከማህበረሰቡ ጋር ያጋሩ",
    "postForm.editSubtitle": "የልጥፍዎን ይዘት እና ማስተካከያዎች ያዘምኑ",
    "postForm.postContent": "የልጥፍ ይዘት",
    "postForm.title": "ርዕስ",
    "postForm.content": "ይዘት",
    "postForm.featuredImage": "የተለየ ምስር URL",
    "postForm.categoriesSettings": "ምድቦች እና ማስተካከያዎች",
    "postForm.category": "ምድብ",
    "postForm.targetAudience": "የተወሰነ ታዳሚ",
    "postForm.status": "ሁኔታ",
    "postForm.scheduleOptions": "መርሐግብር እና አማራጮች",
    "postForm.publishDate": "የማተም ቀን",
    "postForm.expiryDate": "የማብቂያ ቀን",
    "postForm.pinToTop": "ወደ ላይ ሰካ",
    "postForm.pinDescription": "ይህን ልጥፍ ከፊድ ላይ ከላይ ያቆዩ",
    "postForm.tags": "መለያዎች",
    "postForm.addTag": "መለያ ጨምር...",
    "postForm.add": "ጨምር",
    "postForm.cancel": "ሰርዝ",
    "postForm.publishPost": "ልጥፍ ለታተመ",
    "postForm.updatePost": "ልጥፍ አዘምን",
    "postForm.saving": "በማስቀመጥ ላይ...",
    "postForm.requiredFields": "እባክዎ ርዕስ እና ይዘት ይሙሉ",
    "postForm.loginRequired": "ልጥፎችን ለመፍጠር መግባት አለብዎት",
    "postForm.postCreated": "ልጥፍ በተሳካ ሁኔታ ተፈጥሯል!",
    "postForm.postPublished": "ልጥፍዎ ተተምቷል።",
    "postForm.postUpdated": "ልጥፍ በተሳካ ሁኔታ ተዘምኗል!",
    "postForm.postChangesSaved": "ልጥፍዎ ተዘምኗል።",
    "postForm.saveError": "ልጥፍ ማስቀመጥ አልተሳካም",
    // "postForm.categories": {
    //   "announcement": "ማስታወቂያ",
    //   "lesson": "ትምህርት",
    //   "event": "ክስተት",
    //   "general": "አጠቃላይ"
    // },
    // "postForm.audience": {
    //   "all": "ሁሉም",
    //   "students": "ተማሪዎች ብቻ",
    //   "teachers": "አስተማሪዎች ብቻ",
    //   "parents": "ወላጆች ብቻ"
    // },
    // "postForm.statuses": {
    //   "draft": "ረቂቅ",
    //   "published": "የተተረጎመ",
    //   "archived": "ተጠርቷል"
    // },

    "userForm.createTitle": "አዲስ ተማሪ ይመዝገቡ",
    "userForm.editTitle": "የተጠቃሚ መገለጫ አዘምን",
    "userForm.createSubtitle": "አዲስ ተማሪ ለመመዝገብ ሁሉንም የሚያስፈልጉ መረጃዎች ይሙሉ",
    "userForm.editSubtitle": "የተጠቃሚ መረጃ እና የግል ዝርዝሮች አዘምን",
    "userForm.editingOwnProfile": "የራስዎን መገለጫ እያስተካከሉ ነው",
    "userForm.personalInfo": "የግል መረጃ",
    "userForm.studentId": "የተማሪ መታወቂያ",
    "userForm.firstName": "ስም",
    "userForm.middleName": "የአባት ስም",
    "userForm.lastName": "የአያት ስም",
    "userForm.sex": "ጾታ",
    "userForm.male": "ወንድ",
    "userForm.female": "ሴት",
    "userForm.email": "ኢሜይል አድራሻ",
    "userForm.phone": "ስልክ ቁጥር",
    "userForm.dateOfBirth": "የልደት ቀን",
    "userForm.nationalId": "የብሄር መታወቂያ",
    "userForm.occupation": "ሙያ",
    "userForm.marriageStatus": "የጋብቻ ሁኔታ",
    "userForm.single": "ያላገባ",
    "userForm.married": "ያገባ",
    "userForm.divorced": "የተፋታ",
    "userForm.widowed": "የተሰወረ",
    "userForm.disabilityInfo": "የእገዳ መረጃ",
    "userForm.hasDisability": "እገዳ አለ?",
    "userForm.disabilityType": "የእገዳ አይነት",
    "userForm.locationInfo": "አድራሻ",
    "userForm.country": "አገር",
    "userForm.region": "ክልል",
    "userForm.zone": "ዞን",
    "userForm.woreda": "ወረዳ",
    "userForm.church": "ቤተክርስቲያን",
    "userForm.parentInfo": "ወላጅ/መጠባበቂያ",
    "userForm.parentStatus": "የወላጅ ሁኔታ",
    "userForm.bothParents": "ሁለቱም ወላጆች",
    "userForm.motherOnly": "እናት ብቻ",
    "userForm.fatherOnly": "አባት ብቻ",
    "userForm.guardian": "መጠባበቂያ",
    "userForm.parentFullName": "ሙሉ ስም",
    "userForm.parentEmail": "ኢሜይል",
    "userForm.parentPhone": "ስልክ ቁጥር",
    "userForm.cancel": "ሰርዝ",
    "userForm.createStudent": "ተማሪ ፍጠር",
    "userForm.updateProfile": "መገለጫ አዘምን",
    "userForm.saving": "በማስቀመጥ ላይ...",
    "userForm.requiredFields": "እባክዎ ሁሉንም የሚያስፈልጉ መስኮች ይሙሉ",
    "profile.title": "የመገለጫ ማስተካከያዎች",
    "profile.subtitle": "የግል መረጃዎትን እና የመለያ ማስተካከያዎችን ያስተዳድሩ",
    "profile.editingProfile": "መገለጫዎን እያስተካከሉ ነው",
    "profile.personalInfo": "የግል መረጃ",
    "profile.locationInfo": "የአድራሻ መረጃ",
    "profile.accountSecurity": "የመለያ ደህንነት",
    "profile.changePassword": "የይለፍ ቃል ቀይር",
    "profile.currentPassword": "አሁን ያለው የይለፍ ቃል",
    "profile.newPassword": "አዲስ የይለፍ ቃል",
    "profile.confirmPassword": "አዲሱን የይለፍ ቃል አረጋግጥ",
    "profile.passwordRequirements": "የይለፍ ቃል መስፈርቶች",
    "profile.passwordRequirement1": "ቢያንስ 8 ፊደሎች ርዝም",
    "profile.passwordRequirement2": "አቢይ እና ትንሽ ፊደሎች ያካትቱ",
    "profile.passwordRequirement3": "ቢያንስ አንድ ቁጥር ያካትቱ",
    "profile.passwordRequirement4": "ቢያንስ አንድ ልዩ ፊደል ያካትቱ",
    "profile.memberStats": "የአባል ስታቲስቲክስ",
    "profile.attendance": "መገኘት",
    "profile.activities": "እንቅስቃሴዎች",
    "profile.memberSince": "ከዚህ ጊዜ ጀምሮ አባል",
    "profile.sundaySchoolMember": "የእሁድ ትምህርት ቤት አባል",
    "profile.joined": "ተቀላቅሏል",
    "profile.saveChanges": "ለውጦችን አስቀምጥ",
    "profile.updating": "በማዘመን ላይ...",
    "profile.saving": "በማስቀመጥ ላይ...",
    "profile.profilePictureUpdated": "የመገለጫ ፎቶ ተዘምኗል",
    "profile.photoSaved": "አዲሱ ፎቶዎ ተሰቅሏል",
    "profile.fileTooLarge": "ፋይሉ በጣም ትልቅ ነው",
    "profile.fileSizeError": "እባክዎ ከ5MB ያነሰ ምስር ይምረጡ",
    "profile.passwordsNoMatch": "የይለፍ ቃላት አይጣጣሙም",
    "profile.passwordTooShort": "የይለፍ ቃል ቢያንስ 8 ፊደሎች ርዝም መሆን አለበት",
    "profile.passwordUpdated": "የይለፍ ቃል በተሳካ ሁኔታ ተዘምኗል",
    "profile.passwordChangeSuccess": "የይለፍ ቃልዎ ተቀይሯል",
    "profile.passwordChangeError": "የይለፍ ቃል ማዘመን አልተሳካም",
    "profile.passwordCheckError": "እባክዎ የአሁኑ የይለፍ ቃልዎን ያረጋግጡ እና እንደገና ይሞክሩ",
    "profile.profileUpdated": "መገለጫ በተሳካ ሁኔታ ተዘምኗል",
    "profile.changesSaved": "ለውጦችዎ ተሰቅለዋል",
    "profile.updateError": "መገለጫ ማዘመን አልተሳካም",
    // Add these to the 'am' translations object:
    "profile.editProfile": "መገለጫዎን ያርትዑ",
    "profile.updatePersonalInfo": "የግል መረጃዎትን፣ የአደራረግ ዝርዝሮች እና ምርጫዎች ያዘምኑ",
    "profile.accountSecurityDesc":
      "መለያዎ በቅርብ ጊዜ የተመጡ የማመስጠር ደረጃዎች የተጠበቀ ነው። መደበኛ የደህንነት ማዘመኛዎች ውሂብዎ የተጠበቀ መሆኑን ያረጋግጣሉ።",
    "profile.lastUpdated": "የመጨረሻ ማዘመኛ",
    "profile.membership": "አባልነት",
    "profile.studentId": "የተማሪ መታወቂያ",
    "profile.status": "ሁኔታ",
    "profile.currentGrade": "የአሁኑ ክፍል",
    "profile.loadingProfile": "መገለጫ በመጫን ላይ...",
    "profile.tryAgainLater": "እባክዎ በኋላ ይሞክሩ።",

    "common.save": "ለውጦችን አስቀምጥ",
    "common.cancel": "ሰርዝ",
    "common.delete": "አጥፋ",
    "common.edit": "አርትዕ",
    "common.search": "ፈልግ",
    "common.actions": "እርምጃዎች",
    "common.status": "ሁኔታ",
    "common.role": "ሚና",
    "common.active": "ንቁ",
    "common.inactive": "ንቁ ያልሆነ",

    "user.studentId": "የተማሪ መታወቂያ",
    "user.middleName": "የአባት ስም",
    "user.sex": "ጾታ",
    "user.phoneNumber": "ስልክ ቁጥር",
    "user.disability": "እገዳ",
    "user.disabilityType": "የእገዳ አይነት",
    "user.dateOfBirth": "የልደት ቀን",
    "user.region": "ክልል",
    "user.zone": "ዞን",
    "user.woreda": "ወረዳ",
    "user.church": "ቤተክርስቲያን",
    "user.marriageStatus": "የጋብቻ ሁኔታ",
    "user.parentStatus": "የወላጅ ሁኔታ",
    "user.parentFullName": "ወላጅ ሙሉ ስም",
    "user.parentEmail": "ወላጅ ኢሜይል",
    "user.parentPhoneNumber": "ወላጅ ስልክ",
    "user.nationalId": "የብሄር መታወቂያ",
    "user.occupation": "ሙያ",
    "profile.updateInfo": "የግል መረጃዎትን ያርትዑ",
    "users.noUsersSelected": "ምንም ተጠቃሚ አልተመረጠም",
    "users.cannotDeleteOwnAccount": "የራስዎን መለያ መሰረዝ አይችሉም",
    "users.deletedSuccess": "{{count}} ተጠቃሚ(ዎች) በተሳካ ሁኔታ ተሰርዘዋል",
    "users.userDeleted": "ተጠቃሚ ተሰርቷል",
    "users.admins": "አስተዳዳሪዎች",
    "users.allStatus": "ሁሉም ሁኔታ",
    "users.allRoles": "ሁሉም ሚናዎች",
    "users.exportUsers": "ተጠቃሚዎችን ወደ ውጪ ላክ",
    "users.noUsersFound": "ተጠቃሚ አልተገኘም",
    "users.tryAdjustingSearch": "የፍለጋ ቃላትዎን ይስተካከሉ",
    "users.noUsersAvailable": "በስርዓቱ ውስጥ ምንም ተጠቃሚ የለም",
    "users.userDetails": "የተጠቃሚ ዝርዝሮች",
    "userForm.userUpdated": "ተጠቃሚ በተሳካ ሁኔታ ተዘምኗል",
    "userForm.userCreated": "ተጠቃሚ በተሳካ ሁኔታ ተፈጥሯል",

    "dashboard.overview": "የእሁድ ትምህርት ቤት አስተዳደር ስርዓት አጠቃላይ እይታ",
    "dashboard.totalUsers": "ጠቅላላ ተጠቃሚዎች",
    "dashboard.totalAssets": "ጠቅላላ ንብረቶች",
    "dashboard.activePosts": "ንቁ መልዕክቶች",
    // In the 'am' translations object:
    "dashboard.welcomeMessage":
      "እንኳን በደህና ተመለሱ፣ {{name}}! ዛሬ ምን እየተደረገ እንዳለ እዚህ አለ።",
    "dashboard.usersDescription": "የተመዘገቡ ተጠቃሚዎች",
    "dashboard.assetsDescription": "የቤተክርስቲያን ንብረቶች",
    "dashboard.postsDescription": "ንቁ መልዕክቶች",
    "dashboard.engagementDescription": "የተጠቃሚ ተሳትፎ",
    "dashboard.activeUsers": "ንቁ ተጠቃሚዎች",
    "dashboard.livePosts": "ቀጥታ መልዕክቶች",
    "dashboard.availableAssets": "የሚገኙ ንብረቶች",
    "dashboard.newUserRegistered": "አዲስ ተጠቃሚ ተመዝግቧል",
    "dashboard.assetUpdated": "ንብረት ተዘምኗል",
    "dashboard.newPostPublished": "አዲስ ልጥፍ ተተምቷል",
    "dashboard.userProfileUpdated": "የተጠቃሚ መገለጫ ተዘምኗል",
    "dashboard.hoursAgo": "{{hours}} ሰዓት በፊት",
    "dashboard.daysAgo": "{{days}} ቀን በፊት",
    // "dashboard.quickActions": {
    //   "title": "ፈጣን እርምጃዎች",
    //   "subtitle": "በተደጋጋሚ ጥቅም ላይ የሚውሉ ተግባራት",
    //   "addUser": "አዲስ ተጠቃሚ ያክሉ",
    //   "addUserDesc": "አዲስ ተማሪ ወይም አስተማሪ ይመዝገቡ",
    //   "manageAssets": "ንብረቶችን ያስተዳድሩ",
    //   "manageAssetsDesc": "የቤተክርስቲያን ንብረቶችን ይመልከቱ እና ያስተዳድሩ",
    //   "createPost": "ልጥፍ ይፍጠሩ",
    //   "createPostDesc": "ዜና እና ማስታወቂያዎችን ያጋሩ",
    //   "viewReports": "ሪፖርቶችን ይመልከቱ",
    //   "viewReportsDesc": "ትንታኔዎች እና ግንዛቤዎች"
    // },
    "dashboard.recentActivity": "የቅርብ ሰዓት እንቅስቃሴ",
    "dashboard.recentActivitySubtitle": "የቅርብ ጊዜ የስርዓት እንቅስቃሴዎች",
    "dashboard.viewDetails": "ዝርዝሮችን ይመልከቱ",
    "dashboard.systemOverview": "የስርዓት አጠቃላይ እይታ",
    "dashboard.systemOverviewSubtitle": "የአፈጻጸም መለኪያዎች እና ግንዛቤዎች",
    "dashboard.systemUptime": "የስርዓት እንቅስቃሴ",
    "dashboard.last30Days": "ያለፉት 30 ቀናት",
    "dashboard.activeMonitoring": "ንቁ ቁጥጥር",
    "dashboard.realTimeUpdates": "በቀጥታ ማዘመኛዎች",
    "dashboard.dataAccuracy": "የውሂብ ትክክለኛነት",
    "dashboard.verifiedInformation": "የተረጋገጠ መረጃ",

    // Add these to the 'am' translations object:
    "userDashboard.welcomeBack": "እንኳን በደህና ተመለሱ, {{name}}!",
    "userDashboard.welcomeMessage":
      "ዛሬ በእሁድ ትምህርት ቤት ጉዞዎ ውስጥ ምን እየተደረገ እንዳለ እዚህ አለ።",
    "userDashboard.currentGrade": "የአሁኑ ክፍል",
    "userDashboard.streakDays": "የተከታታይ ቀናት",
    "userDashboard.yourChurch": "ቤተክርስቲያንዎ",
    "userDashboard.myClasses": "የእኔ ክፍሎች",
    "userDashboard.activeEnrollments": "ንቁ ምዝገባዎች",
    "userDashboard.assignedAssets": "የተመደቡ ንብረቶች",
    "userDashboard.resourcesAssigned": "ለእርስዎ የተመደቡ ሀብቶች",
    "userDashboard.attendance": "መገኘት",
    "userDashboard.thisMonth": "ይህ ወር",
    "userDashboard.activities": "እንቅስቃሴዎች",
    "userDashboard.completedThisYear": "በዚህ ዓመት የተጠናቀቁ",
    "userDashboard.quickActions": "ፈጣን እርምጃዎች",
    "userDashboard.viewAnnouncements": "ማስታወቂያዎችን ይመልከቱ",
    "userDashboard.checkLatestNews": "የቅርብ ጊዜ ዜና እና ማዘመኛዎችን ይመልከቱ",
    "userDashboard.updateProfile": "መገለጫ አዘምን",
    "userDashboard.keepInformationCurrent": "መረጃዎን ዘምነው ይቆጥሩ",
    "userDashboard.myResources": "የእኔ ሀብቶች",
    "userDashboard.viewAssignedBooks": "የተመደቡ መጽሐፍት እና ቁሳቁሶችን ይመልከቱ",
    "userDashboard.classSchedule": "የክፍል መርሐግብር",
    "userDashboard.viewTimetable": "የክፍል ሰዓት ሰንጠረዥዎን ይመልከቱ",
    "userDashboard.upcomingEvents": "የሚመጡ ክስተቶች",
    "userDashboard.bibleStudySession": "የመጽሐፍ ቅዱስ ጥናት ክፍል",
    "userDashboard.youthFellowship": "የወጣቶች ማኅበር",
    "userDashboard.sundayService": "የእሁድ አገልግሎት",
    "userDashboard.mainHall": "ዋና አዳራሽ",
    "userDashboard.youthCenter": "የወጣቶች ማዕከል",
    "userDashboard.mainChurch": "ዋና ቤተክርስቲያን",
    "userDashboard.class": "ክፍል",
    "userDashboard.event": "ክስተት",
    "userDashboard.service": "አገልግሎት",
    "userDashboard.recentAnnouncements": "የቅርብ ጊዜ ማስታወቂያዎች",
    "userDashboard.noAnnouncements": "እስካሁን ማስታወቂያ የለም",
    "userDashboard.checkBackLater": "ለማዘመኛዎች በኋላ ይመልከቱ",
    "userDashboard.viewAllAnnouncements": "ሁሉንም ማስታወቂያዎች ይመልከቱ",
    "userDashboard.learningProgress": "የትምህርት እድገት",
    "userDashboard.currentLevel": "የአሁኑ ደረጃ",
    "userDashboard.gradeIntermediate": "ክፍል 3 - መካከለኛ",
    "userDashboard.bibleKnowledge": "የመጽሐፍ ቅዱስ እውቀት",
    "userDashboard.prayerWorship": "ጸሎት እና አምልኮ",
    "userDashboard.churchHistory": "የቤተክርስቲያን ታሪክ",
    "userDashboard.badges": "ባጆች",
    "userDashboard.goalsMet": "የተፈጸሙ ግቦች",
    "userDashboard.sessions": "ክፍለ ጊዜያት",
    "userDashboard.level": "ደረጃ",

    "users.manage": "ተጠቃሚዎችን ያስተዳድሩ",
    "users.viewManage": "ሁሉንም የተመዘገቡ ተጠቃሚዎችን ይመልከቱ እና ያስተዳድሩ",

    "assets.manage": "ንብረቶችን ያስተዳድሩ",
    "assets.overview": "ሁሉንም የቤተክርስቲያን ንብረቶች ይከታተሉ እና ያስተዳድሩ",
    "assetForm.createTitle": "አዲስ ንብረት ይመዝገቡ",
    "assetForm.editTitle": "ንብረት አዘምን",
    "assetForm.createSubtitle": "አዲስ ንብረት ወደ ቤተክርስቲያን ክምችት ያክሉ",
    "assetForm.editSubtitle": "የንብረት መረጃ እና ዝርዝሮች ያዘምኑ",
    "assetForm.basicInfo": "መሰረታዊ መረጃ",
    "assetForm.assetCode": "የንብረት ኮድ",
    "assetForm.assetName": "የንብረት ስም",
    "assetForm.description": "መግለጫ",
    "assetForm.category": "ምድብ",
    "assetForm.status": "ሁኔታ",
    "assetForm.assignedTo": "የተመደበለት",
    "assetForm.condition": "እርማት",
    "assetForm.purchaseDetails": "የግዢ ዝርዝሮች",
    "assetForm.purchaseDate": "የግዢ ቀን",
    "assetForm.purchasePrice": "የግዢ ዋጋ",
    "assetForm.supplier": "ሻጭ",
    "assetForm.locationId": "አድራሻ እና መታወቂያ",
    "assetForm.location": "አድራሻ",
    "assetForm.serialNumber": "ተከታታይ ቁጥር",
    "assetForm.warrantyExpiry": "የዋስትና ጊዜ መጨረሻ",
    "assetForm.tags": "መለያዎች",
    "assetForm.addTag": "መለያ ጨምር...",
    "assetForm.add": "ጨምር",
    "assetForm.cancel": "ሰርዝ",
    "assetForm.createAsset": "ንብረት ፍጠር",
    "assetForm.updateAsset": "ንብረት አዘምን",
    "assetForm.saving": "በማስቀመጥ ላይ...",
    "assetForm.requiredFields": "እባክዎ ሁሉንም የሚያስፈልጉ መስኮች ይሙሉ",
    "assetForm.assetCreated": "ንብረት በተሳካ ሁኔታ ተፈጥሯል!",
    "assetForm.assetAdded": "ወደ ክምችት ታክሏል።",
    "assetForm.assetUpdated": "ንብረት በተሳካ ሁኔታ ተዘምኗል!",
    "assetForm.assetChangesSaved": "የንብረት መረጃ ተዘምኗል።",
    "assetForm.saveError": "ንብረት ማስቀመጥ አልተሳካም",
    "assets.totalAssets": "ጠቅላላ ንብረቶች",
    "assets.available": "ይገኛል",
    "assets.assigned": "ተመድቧል",
    "assets.allStatus": "ሁሉም ሁኔታ",
    "assets.allCategories": "ሁሉም ምድቦች",
    "assets.assetDetails": "የንብረት ዝርዝሮች",
    "assets.condition": "እርማት",
    "assets.noAssetsFound": "ንብረት አልተገኘም",
    "assets.tryAdjustingSearch": "የፍለጋ ቃላትዎን ይስተካከሉ",
    "assets.noAssetsAvailable": "በስርዓቱ ውስጥ ምንም ንብረት የለም",
    "assets.exportAssets": "ንብረቶችን ወደ ውጪ ላክ",
    "assets.deleteSelected": "የተመረጡትን ሰርዝ",
    "assets.registerNewAsset": "አዲስ ንብረት ይመዝገቡ",
    "assets.editAsset": "ንብረት አርትዕ",
    "assets.notAssigned": "አልተመደበም",
    "assets.unknownUser": "ያልታወቀ ተጠቃሚ",
    // "assetForm.categories": {
    //   "Books": "መጽሐፍት",
    //   "Furniture": "የቤት እቃዎች",
    //   "Electronics": "ኤሌክትሮኒክስ",
    //   "Musical Instruments": "የሙዚቃ መሳርያዎች",
    //   "Teaching Materials": "የትምህርት መሳርያዎች",
    //   "Sports Equipment": "የስፖርት መሳርያዎች",
    //   "Kitchen Supplies": "የማእድ እቃዎች",
    //   "Cleaning Supplies": "የማጽጃ እቃዎች",
    //   "Office Supplies": "የቢሮ እቃዎች",
    //   "Religious Items": "የሃይማኖት እቃዎች",
    //   "Audio Visual": "ኦዲዮ ቪዥን",
    //   "Computers": "ኮምፒውተሮች",
    //   "Vehicles": "ተሽከርካሪዎች",
    //   "Other": "ሌሎች"
    // },
    // "assetForm.statuses": {
    //   "available": "ይገኛል",
    //   "assigned": "ተመድቧል",
    //   "maintenance": "በጥገና",
    //   "retired": "ተሰርዟል"
    // },
    // "assetForm.conditions": {
    //   "excellent": "በጣም ጥሩ",
    //   "good": "ጥሩ",
    //   "fair": "መጠነኛ",
    //   "poor": "መቼው"
    // }

    "posts.manage": "ዜና ያስተዳድሩ",
    "posts.overview": "የዜና መልዕክቶችን ይፍጠሩ እና ያስተዳድሩ",
    "posts.totalPosts": "ጠቅላላ ልጥፎች",
    "posts.published": "የተተረጎመ",
    "posts.pinned": "የተሰካ",
    "posts.allStatus": "ሁሉም ሁኔታ",
    "posts.allCategories": "ሁሉም ምድቦች",
    "posts.allAudiences": "ሁሉም ታዳሚዎች",
    "posts.engagement": "አገናኝ",
    "posts.audience": "ታዳሚ",
    "posts.noPostsFound": "ልጥፍ አልተገኘም",
    "posts.tryAdjustingSearch": "የፍለጋ ቃላትዎን ይስተካከሉ",
    "posts.noPostsAvailable": "በስርዓቱ ውስጥ ምንም ልጥፍ የለም",
    "posts.exportPosts": "ልጥፎችን ወደ ውጪ ላክ",
    "posts.deleteSelected": "የተመረጡትን ሰርዝ",
    "posts.createNewPost": "አዲስ ልጥፍ ፍጠር",
    "posts.editPost": "ልጥፍ አርትዕ",
    "posts.tableView": "ሰንጠረዥ",
    "posts.cardView": "ካርዶች",
    "posts.postDetails": "የልጥፍ ዝርዝሮች",
    "posts.justNow": "አሁን በትክ",
    "posts.minutesAgo": "ደቂቃ በፊት",
    "posts.hoursAgo": "ሰዓት በፊት",
    "posts.daysAgo": "ቀን በፊት",
    // In the 'am' translations object:
    "notFound.title": "ገጹ አልተገኘም",
    "notFound.description":
      "ወይዛ! የሚፈልጉት ገጽ ወደ ዲጂታል በረሃ ተሰደደ ይመስላል። ወደ ትክክለኛው መንገድ እንመለስ።",
    "notFound.goBack": "ተመለስ",
    "notFound.homePage": "ዋና ገጽ",
    "notFound.errorCode": "የስህተት ኮድ",
    "notFound.pagesHere": "ገጾች እዚህ",
    "notFound.possibilities": "ዕድሎች",
    "notFound.searchSuggestionTitle": "የሚፈልጉትን ማግኘት አይችሉም?",
    "notFound.searchSuggestionDescription":
      "የፍለጋ ባህሪውን ይጠቀሙ ወይም የማህበረሰባችንን መድረክ ለማሰስ በምናሙ ይሂዱ።",
    "notFound.helpTitle": "በማሰስ ረገድ እርዳታ ይፈልጋሉ?",
    "notFound.helpDescription": "እዚህ ሊፈልጉት የሚችሉ አንዳንድ ታዋቂ ክፍሎች አሉ፡-",
    "notFound.contactSupport": "አሁንም ጠፍተዋል?",
    "notFound.contactLink": "ድጋፍ ያግኙ",
    // Add these to the 'am' translations object:
    "whatsNew.title": "አዲስ ምንድን ነው",
    "whatsNew.subtitle": "የቅርብ ጊዜ ማስታወቂያዎች፣ ትምህርቶች እና ክስተቶች ከቤተክርስቲያን ማህበረሰብዎ",
    "whatsNew.totalPosts": "ጠቅላላ ልጥፎች",
    "whatsNew.pinned": "የተሰካ",
    "whatsNew.announcements": "ማስታወቂያዎች",
    "whatsNew.searchPlaceholder": "ልጥፎችን ይፈልጉ...",
    "whatsNew.allCategories": "ሁሉም ምድቦች",
    "whatsNew.pinnedAnnouncements": "የተሰኙ ማስታወቂያዎች",
    "whatsNew.allCommunityPosts": "ሁሉም የማህበረሰብ ልጥፎች",
    "whatsNew.noPostsFound": "ልጥፍ አልተገኘም",
    "whatsNew.tryAdjustingSearch": "የፍለጋ ቃላትዎን ይስተካከሉ",
    "whatsNew.noPostsAvailable": "በአሁኑ ጊዜ ምንም ልጥፍ የለም",
    "whatsNew.addComment": "አስተያየት ያስገቡ...",
    "whatsNew.postComment": "አስተያየት ለጥፍ",
    "whatsNew.comments": "አስተያየቶች",
    "whatsNew.viewAllComments": "ሁሉንም አስተያየቶች ይመልከቱ",
    "whatsNew.hideComments": "አስተያየቶችን ደብቅ",
    "whatsNew.loadingComments": "አስተያየቶች በመጫን ላይ...",
    "whatsNew.commentPosted": "አስተያየት በተሳካ ሁኔታ ተለጥፏል",
    "whatsNew.failedToPost": "አስተያየት ማስገባት አልተሳካም",
    // Add these to the 'am' translations object:
    "postCard.by": "በ",
    "postCard.pinned": "የተሰካ",
    "postCard.announcement": "ማስታወቂያ",
    "postCard.lesson": "ትምህርት",
    "postCard.event": "ክስተት",
    "postCard.students": "ተማሪዎች",
    "postCard.teachers": "አስተማሪዎች",
    "postCard.parents": "ወላጆች",
    "postCard.everyone": "ሁሉም",
    "postCard.likes": "ፍቅር",
    "postCard.comments": "አስተያየቶች",
    "postCard.shares": "ማጋራት",
    "postCard.like": "ውደዱ",
    "postCard.comment": "አስተያየት",
    "postCard.share": "አጋራ",
    "postCard.writeComment": "አስተያየት ይጻፉ...",
    "postCard.commentsTitle": "አስተያየቶች",
    "postCard.justNow": "አሁን በትክ",
    "postCard.minutesAgo": "ደቂቃ በፊት",
    "postCard.hoursAgo": "ሰዓት በፊት",
    "postCard.daysAgo": "ቀን በፊት",
    "postCard.loginToLike": "ልጥፎችን ለመውደድ እባክዎ ይግቡ",
    "postCard.loginToComment": "አስተያየት ለመስጠት እባክዎ ይግቡ",
    "postCard.writeCommentError": "እባክዎ አስተያየት ይጻፉ",
    "postCard.commentAdded": "አስተያየት በተሳካ ሁኔታ ተጨምሯል!",
    "postCard.failedToComment": "አስተያየት ማስገባት አልተሳካም",
    "postCard.loginToLikeComment": "አስተያየቶችን ለመውደድ እባክዎ ይግቡ",
  },
  om: {
    // Afaan Oromo translations
    "nav.userPortal": "Portaala Fayyadamichaa",

    "nav.dashboard": "Daashboorduu",
    "nav.users": "Fayyadamaawwan Gargaaru",
    "nav.assets": "Qabeenyaawwan Gargaaru",
    "nav.posts": "Oduu Dhiheessuu",
    "nav.profile": "Pirofaayilii Haaraa",
    "nav.whatsNew": "Waan Haaraa Maali?",
    "nav.addUser": "Fayyadamaa Haaraa Dabalatu",
    "nav.adminPortal": "Portaala Misoomaa",

    "auth.login": "Seenuu",
    "auth.signup": "Galmeeffachuu",
    "auth.email": "Imeelii",
    "auth.password": "Jecha Iccitiin",
    "auth.welcome": "Baga Portal Mana Barumsa Jirmaa Geessan",
    "auth.logout": "Ba'i",
    "auth.welcomeDescription":
      "Haala hawaasaa keessan seenuu dhiisee deebi'aa. Imalaa keessan itti fufuuf seenaa.",
    "auth.emailPlaceholder": "imeelii@fake.com",
    "auth.passwordPlaceholder": "••••••••",
    "auth.rememberMe": "Na yaadadhu",
    "auth.forgotPassword": "Jecha icciitii irraanfatte?",
    "auth.signingIn": "Seenuu keessatti...",
    "auth.noAccount": "Akkaawuntii hin qabduu?",
    "auth.admin": "Misoomaa",
    "auth.logoutDesc": "Akkaawuntii kee irraa ba'i",
    "auth.lastLogin": "Seenuu dhumaa",
    // Add these to the existing 'om' translations
    "auth.demoCredentials": "Mallattoo Agarsiisaa",
    "auth.adminAccess": "Dhaabbannaa Misoomaa",
    "auth.memberAccess": "Dhaabbannaa Fayyadamichaa",
    "auth.communityText":
      "Hawaasa keenya haala hawaasaa dhuunfaa irraa makamuun makamu",
    "auth.weeklySessions": "Taphoota Torbanii",
    "auth.satisfaction": "Gammachuu",
    "auth.support": "Gargaarsa",
    // Add these to the existing 'om' translations
    "signup.title": "Maatii Keenya Haala Hawaasaa Irraa Makamuun Makamu",
    "signup.subtitle":
      "Imalaa keessan hawaasa mana barumsa Jirmaa keenya waliin jalqabaa. Galmeeffannoo keessan guutuu qajeelfama hawaasaa, barannoo, fi damee gargaarsa deeggarsa argachuuf.",
    "signup.spiritualBenefits": "Faayidaa Hawaasaa",
    "signup.bibleLearning": "Barumsa Kitaaba Irratti Hundaa'e",
    "signup.bibleLearningDesc":
      "Barannoo qophaa'e barsiisota kitaabaa hubachuufi jireenya guyyaa guyyaa keessatti hojiirra oolchu si gargaaru.",
    "signup.faithCommunity": "Hawaasa Imaanaa",
    "signup.faithCommunityDesc":
      "Namoota sammuu waliigalaa qaban waliin walqunnamuu fi qophii hawaasaa waliigalaa qoodu.",
    "signup.personalGrowth": "Guddina Dhuunfaa",
    "signup.personalGrowthDesc":
      "Qabiyyeewwan fi meeshaalee guddina hawaasaa kee sadarkaa hunda irratti deeggarsu.",
    "signup.communitySupport": "Deeggarsa Hawaasaa",
    "signup.prayerGroups": "Gareewwan Kadhaa",
    "signup.familyEvents": "Taate Maatii",
    "signup.mentorshipPrograms": "Piroogiraamoon Gorsaa",
    "signup.spiritualGuidance": "Qajeelfama Hawaasaa",
    "signup.safeEnvironment": "Naannoo Nageenya Qaba",
    "signup.safeEnvironmentDesc":
      "Plateformi keenya sadarkaa ol'aanaa nageenyaa fi iccitiin qabata. Dalagaan hunda naannoo nageenya hawaasaa namoota hundaaf mirkaneessuuf ni hordofama.",
    "signup.studentRegistration": "Galmeeffannoo Barataa",
    "signup.registrationDesc":
      "Galmeeffannoo imalaa hawaasaa kee guutuuf odeeffannoo barbaachisaa hunda kenni",
    "signup.backToLogin": "Seenuu Deebi'i",

    "userForm.createTitle": "Barataa Haaraa Galmeessuu",
    "userForm.editTitle": "Pirofaayilii Fayyadamichaa Haaraa",
    "userForm.createSubtitle":
      "Barataa haaraa galmeessuuf odeeffannoo barbaachisaa hunda guutuu",
    "userForm.editSubtitle":
      "Odeeffannoo fayyadamichaa fi gulaalta dhuunfaa haaraa",
    "userForm.editingOwnProfile": "Pirofaayilii Keessan Gulaaluu",
    "userForm.personalInfo": "Odeeffannoo Dhuunfaa",
    "userForm.studentId": "ID Barataa",
    "userForm.firstName": "Maqaa",
    "userForm.middleName": "Maqaa Gidduu",
    "userForm.lastName": "Maqaa Firaa",
    "userForm.sex": "Saala",
    "userForm.male": "Dhiira",
    "userForm.female": "Dhalaa",
    "userForm.email": "Imeelii",
    "userForm.phone": "Lakkoofsa Bilbila",
    "userForm.dateOfBirth": "Guyyaa Dhalootaa",
    "userForm.nationalId": "ID Aangoo",
    "userForm.occupation": "Hojii",
    "userForm.marriageStatus": "Haala Heerumaa",
    "userForm.single": "Heerumaa Hin Qabne",
    "userForm.married": "Heerume",
    "userForm.divorced": "Hidhaan Cittee",
    "userForm.widowed": "Hidhaan Dhabe",
    "userForm.disabilityInfo": "Odeeffannoo Dhabamaa",
    "userForm.hasDisability": "Dhabama Qaba?",
    "userForm.disabilityType": "Gosa Dhabamaa",
    "userForm.locationInfo": "Bakka",
    "userForm.country": "BiYYaa",
    "userForm.region": "Naannoo",
    "userForm.zone": "Zoone",
    "userForm.woreda": "Aanaa",
    "userForm.church": "Manni Nagaa",
    "userForm.parentInfo": "Maatii/Eeggataa",
    "userForm.parentStatus": "Haala Maatii",
    "userForm.bothParents": "Maatii Lamaanuu",
    "userForm.motherOnly": "Haadha Qofa",
    "userForm.fatherOnly": "Abbaa Qofa",
    "userForm.guardian": "Eeggataa",
    "userForm.parentFullName": "Maqaa Guutuu",
    "userForm.parentEmail": "Imeelii",
    "userForm.parentPhone": "Lakkoofsa Bilbila",
    "userForm.cancel": "Haqi",
    "userForm.createStudent": "Barataa Uumuu",
    "userForm.updateProfile": "Pirofaayilii Haaraa",
    "userForm.saving": "Tiksaa jira...",
    "userForm.requiredFields": "Mee bakkawwan barbaachisaa hunda guuti",
    "profile.title": "Qajeelfama Pirofaayilii",
    "profile.subtitle":
      "Odeeffannoo dhuunfaa kee fi qajeelfama akkaawuntii sirreessi",
    "profile.editingProfile": "Pirofaayilii Keessan Gulaaluu",
    "profile.personalInfo": "Odeeffannoo Dhuunfaa",
    "profile.locationInfo": "Odeeffannoo Bakka",
    "profile.accountSecurity": "Nageenya Akkaawuntii",
    "profile.changePassword": "Jecha Iccitiin Jijjiiraa",
    "profile.currentPassword": "Jecha Iccitiin Ammaa",
    "profile.newPassword": "Jecha Iccitiin Haaraa",
    "profile.confirmPassword": "Jecha Iccitiin Haaraa Mirkaneessi",
    "profile.passwordRequirements": "Filannoo Jecha Iccitiin",
    "profile.passwordRequirement1": "Yartuuuu hangi 8 qabaachuu qaba",
    "profile.passwordRequirement2": "Qubee guddaa fi qubee xinnoo hunda hammi",
    "profile.passwordRequirement3": "Yartuuuuu lakkoofsa tokko hammi",
    "profile.passwordRequirement4": "Yartuuuuu mallattoo adda tokko hammi",
    "profile.memberStats": "Taate Fayyadamichaa",
    "profile.attendance": "Argama",
    "profile.activities": "Hojiiwwan",
    "profile.memberSince": "Fayyadamichaa Eegaluu",
    "profile.sundaySchoolMember": "Fayyadama Mana Barumsa Jirmaa",
    "profile.joined": "Makame",
    "profile.saveChanges": "Jijjiiramaawwan Tiksuu",
    "profile.updating": "Haaraa jira...",
    "profile.saving": "Tiksaa jira...",
    "profile.profilePictureUpdated": "Faayilii Pirofaayilii Haaraa",
    "profile.photoSaved": "Faayilii kee haaraa tiksameera",
    "profile.fileTooLarge": "Faayilii baayyee guddaadha",
    "profile.fileSizeError": "Mee faayilii 5MB caalaa xiqqaa filadhu",
    "profile.passwordsNoMatch": "Jecha icciitin wal hin galchan",
    "profile.passwordTooShort":
      "Jecha icciitin yartuuuu hangi 8 qabaachuu qaba",
    "profile.passwordUpdated": "Jecha icciitin milkaa'inneen jijjiirameera",
    "profile.passwordChangeSuccess": "Jecha icciitin kee jijjiirameera",
    "profile.passwordChangeError": "Jecha icciitin jijjiirachuu hin dandeenye",
    "profile.passwordCheckError":
      "Mee jecha icciitin ammaa kee mirkaneessi yeroo biraa yaali",
    "profile.profileUpdated": "Pirofaayilii milkaa'inneen haaraa",
    "profile.changesSaved": "Jijjiiramaawwan kee tiksamanii jiru",
    "profile.updateError": "Pirofaayilii haaraa gochuun hin dandeenye",
    "profile.updateInfo": "Odeeffannoo dhuunfaa kee gulaali",
    // Add these to the 'om' translations object:
    "profile.editProfile": "Pirofaayilii Keessan Gulaali",
    "profile.updatePersonalInfo":
      "Odeeffannoo dhuunfaa keessan, gulaalta quunnamtii fi filannoo haaraa",
    "profile.accountSecurityDesc":
      "Akkaawuntii keessan sadarkaa icciitii dhihoo waliin nageeffama. Haaraa nageenyaa yeroo yeroo ta'e daataa keessan nageeffamaa jiraachuun mirkaneessa.",
    "profile.lastUpdated": "Haaraa dhumaa",
    "profile.membership": "Fayyadamichaa",
    "profile.studentId": "ID Barataa",
    "profile.status": "Haala",
    "profile.currentGrade": "Sadarkaa Ammaa",
    "profile.loadingProfile": "Pirofaayilii Kuufamaa jira...",
    "profile.tryAgainLater": "Mee booda yaali.",

    "common.save": "Jijjiiramaawwan Tiksuu",
    "common.cancel": "Haqi",
    "common.delete": "Haaluu",
    "common.edit": "Gulaaluu",
    "common.search": "Barbaadi",
    "common.actions": "Hojiiwwan",
    "common.status": "Haala",
    "common.role": "Dhuunfa",
    "common.active": "Hojii irra jira",
    "common.inactive": "Hojii irra hin jirre",

    "user.studentId": "ID Barataa",
    "user.middleName": "Maqaa Gidduu",
    "user.sex": "Saala",
    "user.phoneNumber": "Lakkoofsa Bilbila",
    "user.disability": "Dhabama",
    "user.disabilityType": "Gosa Dhabamaa",
    "user.dateOfBirth": "Guyyaa Dhalootaa",
    "user.region": "Naannoo",
    "user.zone": "Zoone",
    "user.woreda": "Aanaa",
    "user.church": "Manni Nagaa",
    "user.marriageStatus": "Haala Heerumaa",
    "user.parentStatus": "Haala Maatii",
    "user.parentFullName": "Maqaa Guutuu Maatii",
    "user.parentEmail": "Imeelii Maatii",
    "user.parentPhoneNumber": "Bilbila Maatii",
    "user.nationalId": "ID Aangoo",
    "user.occupation": "Hojii",
    "users.noUsersSelected": "Fayyadamichaa hin filatamne",
    "users.cannotDeleteOwnAccount":
      "Akkaawuntii keessan haaluu hin dandeessanu",
    "users.deletedSuccess": "{{count}} fayyadamichaa(n) milkaa'inneen haalamte",
    "users.userDeleted": "Fayyadamichaa haalamte",
    "users.admins": "Misoomaawwan",
    "users.allStatus": "Haala Hundaa",
    "users.allRoles": "Dhuunfa Hundaa",
    "users.exportUsers": "Fayyadamaawwan Baasi",
    "users.noUsersFound": "Fayyadamichaa hin argamne",
    "users.tryAdjustingSearch": "Yaali jecha barbaachisaa keessan gulaali",
    "users.noUsersAvailable": "Fayyadamichaa siisteemii keessatti hin jiru",
    "users.userDetails": "Gulaalta Fay",

    // In the 'om' translations object:
    "auth.logoutSuccess": "Milkaa'inneen ba'anii",
    "nav.settings": "Sirreeffamoo",
    "common.user": "Fayyadamichaa",

    "dashboard.overview": "Daa'imman mana barumsa jirmaa waliigalaa",
    "dashboard.totalUsers": "Waliigala Fayyadamaawwan",
    "dashboard.totalAssets": "Waliigala Qabeenyaawwan",
    "dashboard.activePosts": "Odeeffannoo Hojii irra jiran",
    // In the 'om' translations object:
    "dashboard.welcomeMessage":
      "Baga nagaan deebi'an, {{name}}! Waan har'a raawwatamaa jiru asii jira.",
    "dashboard.usersDescription": "Fayyadamaawwan galmeeffaman",
    "dashboard.assetsDescription": "Qabeenyaawwan mana nagaaas",
    "dashboard.postsDescription": "Mallattoolee hojii irra jiran",
    "dashboard.engagementDescription": "Hirmaannaa fayyadamichaa",
    "dashboard.activeUsers": "Fayyadamaawwan Hojii irra jiran",
    "dashboard.livePosts": "Mallattoolee Sirrii",
    "dashboard.availableAssets": "Qabeenyaawwan Jiran",
    "dashboard.newUserRegistered": "Fayyadamichaa haaraa galmeeffame",
    "dashboard.assetUpdated": "Qabeenya haaraa",
    "dashboard.newPostPublished": "Mallattoo haaraa maxxanfame",
    "dashboard.userProfileUpdated": "Pirofaayilii fayyadamichaa haaraa",
    "dashboard.hoursAgo": "sa'aatii {{hours}} dura",
    "dashboard.daysAgo": "guyyaa {{days}} dura",
    // "dashboard.quickActions": {
    //   "title": "Hojiiwwan Dafaa",
    //   "subtitle": "Hojiiwwan yeroo baay'ee itti fayyadamani",
    //   "addUser": "Fayyadamichaa Haaraa Dabalatu",
    //   "addUserDesc": "Barataa haaraa ykn barsiisaa galmeessi",
    //   "manageAssets": "Qabeenyaawwan Gargaaru",
    //   "manageAssetsDesc": "Qabeenyaawwan mana nagaaas ilaaliifi gargaaru",
    //   "createPost": "Mallattoo Uumuu",
    //   "createPostDesc": "Oduu fi beeksisaawwan qooduu",
    //   "viewReports": "Ripoortii Ilaaluu",
    //   "viewReportsDesc": "Qorannoo fi hubannoo"
    // },
    "dashboard.recentActivity": "Hojii Dhihoo",
    "dashboard.recentActivitySubtitle": "Hojiiwwan siisteemii dhihoo",
    "dashboard.viewDetails": "Gulaalta ilaaluu",
    "dashboard.systemOverview": "Ilaalcha Siisteemii",
    "dashboard.systemOverviewSubtitle": "Sadarkaa hojii fi hubannoo",
    "dashboard.systemUptime": "Yeroo Siisteemii Hojii irra Jirtu",
    "dashboard.last30Days": "Guyyoota 30 darban",
    "dashboard.activeMonitoring": "Hordofii Hojii irra jira",
    "dashboard.realTimeUpdates": "Haaraa yeroo sirriitti",
    "dashboard.dataAccuracy": "Sirna Daatii",
    "dashboard.verifiedInformation": "Odeeffannoo mirkaneeffame",

    // Add these to the 'om' translations object:
    "userDashboard.welcomeBack": "Baga Nagaan Deebi'an, {{name}}!",
    "userDashboard.welcomeMessage":
      "Waan Har'a Imalaa Mana Barumsa Jirmaa Keessatti Raawwatamaa Jiru Asii Jira.",
    "userDashboard.currentGrade": "Sadarkaa Ammaa",
    "userDashboard.streakDays": "Guyyaawwan Tuuta",
    "userDashboard.yourChurch": "Manni Nagaa Keessan",
    "userDashboard.myClasses": "Qotee Bulaa Koo",
    "userDashboard.activeEnrollments": "Galmeeffannoo Hojii irra jiran",
    "userDashboard.assignedAssets": "Qabeenyaawwan Kenname",
    "userDashboard.resourcesAssigned": "Qabeenyaawwan Siif Kenname",
    "userDashboard.attendance": "Argama",
    "userDashboard.thisMonth": "Ji'a Kana",
    "userDashboard.activities": "Hojiiwwan",
    "userDashboard.completedThisYear": "Waggaa Kana Guutame",
    "userDashboard.quickActions": "Hojiiwwan Dafaa",
    "userDashboard.viewAnnouncements": "Beeksisaawwan Ilaaluu",
    "userDashboard.checkLatestNews": "Oduu Fi Haaraa Dhihoo Ilalli",
    "userDashboard.updateProfile": "Pirofaayilii Haaraa",
    "userDashboard.keepInformationCurrent":
      "Odeeffannoo Keessan Ammaa Tursiisaa",
    "userDashboard.myResources": "Qabeenyaan Koo",
    "userDashboard.viewAssignedBooks":
      "Kitaabota Fi Qabiyyeewwan Kenname Ilalli",
    "userDashboard.classSchedule": "Yeroo Qotee Bulaa",
    "userDashboard.viewTimetable": "Maqaa Sa'aatii Qotee Bulaa Keessan Ilalli",
    "userDashboard.upcomingEvents": "Taateen Dhufu",
    "userDashboard.bibleStudySession": "Qophii Kitaaba Barannoo",
    "userDashboard.youthFellowship": "Walitti Qabaa Dargaggeessaa",
    "userDashboard.sundayService": "Taphii Jirmaa",
    "userDashboard.mainHall": "Hallii Guddaa",
    "userDashboard.youthCenter": "Senterii Dargaggeessaa",
    "userDashboard.mainChurch": "Manni Nagaa Guddaa",
    "userDashboard.class": "qotee bulaa",
    "userDashboard.event": "ta'umsa",
    "userDashboard.service": "taphii",
    "userDashboard.recentAnnouncements": "Beeksisaawwan Dhihoo",
    "userDashboard.noAnnouncements": "Amma Beeksisa Hin Jiru",
    "userDashboard.checkBackLater": "Haaraa Eegaluuf Booda Deebi'i",
    "userDashboard.viewAllAnnouncements": "Beeksisaawwan Hunda Ilaaluu",
    "userDashboard.learningProgress": "Jireenya Barannoo",
    "userDashboard.currentLevel": "Sadarkaa Ammaa",
    "userDashboard.gradeIntermediate": "Qotee Bulaa 3 - Giddu-galeessa",
    "userDashboard.bibleKnowledge": "Beekumsa Kitaabaa",
    "userDashboard.prayerWorship": "Kadhaa & Qunnamuu",
    "userDashboard.churchHistory": "Seenaa Manni Nagaa",
    "userDashboard.badges": "Baajiiwwan",
    "userDashboard.goalsMet": "Kaayyoo Guutame",
    "userDashboard.sessions": "Qophiiwwan",
    "userDashboard.level": "Sadarkaa",

    "users.manage": "Fayyadamaawwan Gargaaru",
    "users.viewManage": "Fayyadamaawwan galmeeffaman hunda ilaaliifi gargaaru",

    "assets.manage": "Qabeenyaawwan Gargaaru",
    "assets.overview": "Qabeenyaawwan mana nagaaas hunda hordofifi gargaaru",
    "assetForm.createTitle": "Qabeenya Haaraa Galmeessuu",
    "assetForm.editTitle": "Qabeenya Haaraa",
    "assetForm.createSubtitle":
      "Qabeenya haaraa kuusaa mana nagaa keessatti dabalatu",
    "assetForm.editSubtitle": "Odeeffannoo qabeenyaa fi gulaalta haaraa",
    "assetForm.basicInfo": "Odeeffannoo Bu'uuraa",
    "assetForm.assetCode": "Koodii Qabeenyaa",
    "assetForm.assetName": "Maqaa Qabeenyaa",
    "assetForm.description": "Ibsa",
    "assetForm.category": "Garee",
    "assetForm.status": "Haala",
    "assetForm.assignedTo": "Kenname",
    "assetForm.condition": "Haala",
    "assetForm.purchaseDetails": "Gulaalta Bitaa",
    "assetForm.purchaseDate": "Guyyaa Bitaa",
    "assetForm.purchasePrice": "Gatii Bitaa",
    "assetForm.supplier": "Bitootessa",
    "assetForm.locationId": "Bakka & ID",
    "assetForm.location": "Bakka",
    "assetForm.serialNumber": "Lakkoofsa Siriyaalaa",
    "assetForm.warrantyExpiry": "Xumura Warantii",
    "assetForm.tags": "Mallattoolee",
    "assetForm.addTag": "Mallattoo dabalatu...",
    "assetForm.add": "Dabalatu",
    "assetForm.cancel": "Haqi",
    "assetForm.createAsset": "Qabeenya Uumuu",
    "assetForm.updateAsset": "Qabeenya Haaraa",
    "assetForm.saving": "Tiksaa jira...",
    "assetForm.requiredFields": "Mee bakkawwan barbaachisaa hunda guuti",
    "assetForm.assetCreated": "Qabeenya milkaa'inneen uumameera!",
    "assetForm.assetAdded": "kuusaa keessatti dabalameera.",
    "assetForm.assetUpdated": "Qabeenya milkaa'inneen haaraa!",
    "assetForm.assetChangesSaved": "Odeeffannoo qabeenyaa haaraa.",
    "assetForm.saveError": "Qabeenya tiksachuu hin dandeenye",
    "assets.totalAssets": "Waliigala Qabeenyaawwan",
    "assets.available": "Jira",
    "assets.assigned": "Kenname",
    "assets.allStatus": "Haala Hundaa",
    "assets.allCategories": "Garee Hundaa",
    "assets.assetDetails": "Gulaalta Qabeenyaa",
    "assets.condition": "Haala",
    "assets.noAssetsFound": "Qabeenyi hin argamne",
    "assets.tryAdjustingSearch": "Yaali jecha barbaachisaa keessan gulaali",
    "assets.noAssetsAvailable": "Qabeenyi siisteemii keessatti hin jiru",
    "assets.exportAssets": "Qabeenyaawwan Baasi",
    "assets.deleteSelected": "Filataman Haaluu",
    "assets.registerNewAsset": "Qabeenya Haaraa Galmeessuu",
    "assets.editAsset": "Qabeenya Gulaaluu",
    "assets.notAssigned": "Hin Kenname",
    "assets.unknownUser": "Fayyadamichaa Hin Beekamne",
    // "assetForm.categories": {
    //   "Books": "Kitaabota",
    //   "Furniture": "Meeshaalee Manaa",
    //   "Electronics": "Eleektrooniksii",
    //   "Musical Instruments": "Meeshaalee Muuziqaa",
    //   "Teaching Materials": "Meeshaalee Barsiisaa",
    //   "Sports Equipment": "Meeshaalee Spoorii",
    //   "Kitchen Supplies": "Meeshaalee Mana nyaataa",
    //   "Cleaning Supplies": "Meeshaalee Qulqullinaa",
    //   "Office Supplies": "Meeshaalee Biroo",
    //   "Religious Items": "Meeshaalee Amantaa",
    //   "Audio Visual": "Awudii Fiijii",
    //   "Computers": "Kompiturawwan",
    //   "Vehicles": "Konkolaatawwan",
    //   "Other": "Kan Biroo"
    // },
    // "assetForm.statuses": {
    //   "available": "Jira",
    //   "assigned": "Kenname",
    //   "maintenance": "Tajaajilaa",
    //   "retired": "Dhiifame"
    // },
    // "assetForm.conditions": {
    //   "excellent": "Baayyee Gaarii",
    //   "good": "Gaarii",
    //   "fair": "Giddu-galeessa",
    //   "poor": "Hammaate"
    // }

    "posts.manage": "Oduu Dhiheessuu",
    "posts.overview": "Oduu uumuu fi gargaaruu",
    "posts.totalPosts": "Waliigala Mallattoolee",
    "posts.published": "Maxxanfame",
    "posts.pinned": "Dhiibame",
    "posts.allStatus": "Haala Hundaa",
    "posts.allCategories": "Garee Hundaa",
    "posts.allAudiences": "Daandii Hundaa",
    "posts.engagement": "Walqunnamii",
    "posts.audience": "Daandii",
    "posts.noPostsFound": "Mallattoo hin argamne",
    "posts.tryAdjustingSearch": "Yaali jecha barbaachisaa keessan gulaali",
    "posts.noPostsAvailable": "Mallattoo siisteemii keessatti hin jiru",
    "posts.exportPosts": "Mallattoolee Baasi",
    "posts.deleteSelected": "Filataman Haaluu",
    "posts.createNewPost": "Mallattoo Haaraa Uumuu",
    "posts.editPost": "Mallattoo Gulaaluu",
    "posts.tableView": "Teebila",
    "posts.cardView": "Kaardii",
    "posts.postDetails": "Gulaalta Mallattoo",
    "posts.justNow": "Amma ammaa",
    "posts.minutesAgo": "daqiiqaa dura",
    "posts.hoursAgo": "sa'aatii dura",
    "posts.daysAgo": "guyyaa dura",

    // In the 'om' translations object:
    "notFound.title": "Fuula Hin Argamne",
    "notFound.description":
      "Yaada! Fuula barbaaddan gara dachee dijiitaalaa seenee jira. Gara karaa sirriitti deebina.",
    "notFound.goBack": "Deebi'i",
    "notFound.homePage": "Fuula Ijoo",
    "notFound.errorCode": "Koodii Dogoggoraa",
    "notFound.pagesHere": "Fuulawwan Asii",
    "notFound.possibilities": "Dandeettiiwwan",
    "notFound.searchSuggestionTitle": "Waan barbaaddan arguu hin dandeenye?",
    "notFound.searchSuggestionDescription":
      "Mee tooftaa barbaachisaa fayyadamii ykn menuu keessatti deemi platformii hawaasaa keenya qoo'achuuf.",
    "notFound.helpTitle": "Gargaarsa Qajeelfama Barbaaddaa?",
    "notFound.helpDescription": "Asii gareewwan beekamoo barbaachisuuf jirtan:",
    "notFound.contactSupport": "Ammas dhabamtee?",
    "notFound.contactLink": "Gargaarsa Qunnamuu",

    // Add these to the 'om' translations object:
    "whatsNew.title": "Waan Haaraa Maali?",
    "whatsNew.subtitle":
      "Beeksisaawwan, barannoota fi taateen dhihoo hawaasa mana nagaa keessan irraa",
    "whatsNew.totalPosts": "Waliigala Mallattoolee",
    "whatsNew.pinned": "Dhiibame",
    "whatsNew.announcements": "Beeksisaawwan",
    "whatsNew.searchPlaceholder": "Mallattoolee barbaadi...",
    "whatsNew.allCategories": "Garee Hundaa",
    "whatsNew.pinnedAnnouncements": "Beeksisaawwan Dhiibaman",
    "whatsNew.allCommunityPosts": "Mallattoolee Hawaasa Hundaa",
    "whatsNew.noPostsFound": "Mallattoo hin argamne",
    "whatsNew.tryAdjustingSearch": "Yaali jecha barbaachisaa keessan gulaali",
    "whatsNew.noPostsAvailable": "Amma mallattoo hin jiru",
    "whatsNew.addComment": "Yaada dabalatu...",
    "whatsNew.postComment": "Yaada Dhiheessi",
    "whatsNew.comments": "Yaadannoo",
    "whatsNew.viewAllComments": "Yaadannoo hunda ilaaluu",
    "whatsNew.hideComments": "Yaadannoo dhoksi",
    "whatsNew.loadingComments": "Yaadannoo kuufamaa jira...",
    "whatsNew.commentPosted": "Yaada milkaa'inneen dhiyaate",
    "whatsNew.failedToPost": "Yaada dhiyeessuu hin dandeenye",

    // Add these to the 'om' translations object:
    "postCard.by": "Kan",
    "postCard.pinned": "Dhiibame",
    "postCard.announcement": "Beeksisaa",
    "postCard.lesson": "Barannoo",
    "postCard.event": "Ta'umsa",
    "postCard.students": "Barattootni",
    "postCard.teachers": "Barsiisotni",
    "postCard.parents": "Maatii",
    "postCard.everyone": "Hundumtuu",
    "postCard.likes": "jaalalloo",
    "postCard.comments": "yaadannoo",
    "postCard.shares": "qooduu",
    "postCard.like": "Jaalladhu",
    "postCard.comment": "Yaada",
    "postCard.share": "Qoodi",
    "postCard.writeComment": "Yaada barreessi...",
    "postCard.commentsTitle": "Yaadannoo",
    "postCard.justNow": "Amma ammaa",
    "postCard.minutesAgo": "daqiiqaa dura",
    "postCard.hoursAgo": "sa'aatii dura",
    "postCard.daysAgo": "guyyaa dura",
    "postCard.loginToLike": "Mallattoo jaalachuuf seenaa",
    "postCard.loginToComment": "Yaada kennuuf seenaa",
    "postCard.writeCommentError": "Mee yaada barreessi",
    "postCard.commentAdded": "Yaada milkaa'inneen dabalameera!",
    "postCard.failedToComment": "Yaada dabalchuun hin dandeenye",
    "postCard.loginToLikeComment": "Yaadannoo jaalachuuf seenaa",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem(
      "sundayschool-language"
    ) as Language;
    if (savedLanguage && ["en", "am", "om"].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("sundayschool-language", lang);
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage: handleSetLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
